apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-app-ha
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple_web_app_ha
  template:
    metadata:
      labels:
        app: simple_web_app_ha
    spec:
      containers:
      - name: simple_web_app_ha
        image: vaheed/simple_web_app_ha:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
