apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaheed-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vaheed-web-app
  template:
    metadata:
      labels:
        app: vaheed-web-app
    spec:
      containers:
      - name: vaheed-web-app
        image: vaheed/vaheed-web-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
